apiVersion: v2
name: mlflow
description: A Helm chart for deploying MLflow on Kubernetes/OpenShift
type: application
version: 0.1.0
appVersion: "3.6.0"
keywords:
  - mlflow
  - machine-learning
  - model-registry
home: https://github.com/opendatahub-io/mlflow-operator
maintainers:
  - name: MLflow Operator Maintainers
    url: https://github.com/opendatahub-io/mlflow-operator
