apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: mlflowlink
spec:
  applicationMenu:
    section: MLflow
    imageURL: data:image/svg+xml;base64,PHN2ZyBpZD0iYjQ0ZmI3NTItOWIxZS00MWM4LThiNmItNzBiZDczNGY0NTY1IiBkYXRhLW5hbWU9Imljb243NSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2aWV3Qm94PSIwIDAgMzIgMzIiPgogIDxwYXRoIGQ9Ik0yNy42NzYsMjUuNzgzLDIxLDEwLjc4N1YzaDFhMSwxLDAsMCwwLDAtMkgyMC41QTEuNTAxODMsMS41MDE4MywwLDAsMCwxOSwyLjVWMTFhMS4wMDExNywxLjAwMTE3LDAsMCwwLC4wODYuNDA3TDIyLjAyMSwxOEg5Ljk3N2wyLjkzNS02LjU5M0ExLjAwMTE3LDEuMDAxMTcsMCwwLDAsMTIuOTk4LDExVjIuNWExLjUwMTgzLDEuNTAxODMsMCwwLDAtMS41LTEuNWgtMS41YTEsMSwwLDAsMCwwLDJoMXY3Ljc4OEw0LjMyMiwyNS43ODRhMy43MDgwNywzLjcwODA3LDAsMCwwLDMuMzg3LDUuMjE3SDI0LjI4NmEzLjcwODA3LDMuNzA4MDcsMCwwLDAsMy4zODctNS4yMTdabS0xLjk1NCwyLjQzOUExLjY3ODc3LDEuNjc4NzcsMCwwLDEsMjQuMjg5LDI5SDcuNzExYTEuNzA3NCwxLjcwNzQsMCwwLDEtMS41Ni0yLjQwM0w5LjA4OCwyMEgyMi45MTJsMi45MzcsNi41OTdBMS42ODE2NiwxLjY4MTY2LDAsMCwxLDI1LjcyMiwyOC4yMjJaIiBzdHlsZT0iZmlsbDogIzM3YTNhMyIvPgogIDxyZWN0IGlkPSJhZmJlODc1YS02NGUwLTQ4Y2MtODQ5Mi0xMmVlZjdkOTI0NDEiIGRhdGEtbmFtZT0idHJhbnNwYXJlbnQgcmVjdGFuZ2xlIiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHN0eWxlPSJmaWxsOiBub25lIi8+Cjwvc3ZnPgo=
  href: $(mlflow-url)
  location: ApplicationMenu
  text: MLflow
