apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mlflow
spec:
  parentRefs:
    - name: $(gateway-name)
      kind: Gateway
      namespace: openshift-ingress
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/mlflow"
      backendRefs:
        - name: mlflow
          port: 8443
