{{- if and .Values.kubeRbacProxy .Values.kubeRbacProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-rbac-proxy-config{{ .Values.resourceSuffix }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mlflow
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  config.yaml: |
    authorization:
      resourceAttributes: {}
      static:
        - resourceRequest: true
{{- end }}
